version: '3'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: coletatudo-server
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
    expose:
      - 3000
